### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by rakucmr** [vmoulin78/codeigniter-layout-library#1]
You need yaml just for parent_template parameter?

**Comment by vmoulin78** [comment]
Today, there is only one parameter but in the future, there will certainly be more than one and I didn't find a configuration type as good as YAML.
If you may not install the YAML extension, the alternative is to install a CodeIgniter YAML Library.

**Comment by rakucmr** [comment]
why are not using config files, that can be processed with config codeigniter library?

**Comment by vmoulin78** [comment]
I thought about it and hesitated between the two solutions.
I finally chose YAML because I consider:
- PHP is a processing language
- YAML is a configuration language

And the advantage is that I can have the template file (ex: footer_template.php) and the config file (ex: footer_template.yml) with the same name in the same folder.

**Comment by vmoulin78** [comment]
Maybe, I could manage both solutions:
If there is a config.yml file, I load this file
Otherwise, I load the php file config.php which contains the same data but in the php format

**Comment by vmoulin78** [comment]
Version 3.1.0:
Regarding the configuration file, you can now choose the PHP or YAML format.

**Comment by rakucmr** [comment]
👍 nice, thanks
